<?php

use App\Models\VRPagesTranslations;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PagesTranslationsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $pagesTranslations = [
            ["page_id" => "apie", "language_id" => "lt", "title" => "Apie", "description_short" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems.", "description_long" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems - ir pirmą kartą išmėginsiantiems virtualią realybę, ir tiems, kurie jau žino kas tai yra. 10 skirtingų patirčių ir net 60 minučių įspūdžių, adrenalino ir atradimų laukia kiekvieno apsilankiusiojo. Paruošėme trijų skirtingų sudėtingumo lygių patirtis - nuo irklavimo Galvės ežere ar leidimosi parašiutu iki Mini golfo žaidimo ant pilies sienų ar stebuklingo gėrimo gamybos. Tačiau neabejojame, jog norėsi išbandyti visas. Virtuali realybė suteikia progą pažvelgti į pasaulį kitomis akimis ir iš paprasto stebėtojo virsti veiksmo dalyviu. Aukštos kokybės grafika, realūs vaizdai ir galimybė interaktyviai dalyvauti patirtyje tiesiog įtraukia! Tad ateik, užsidėk VR akinius ir atsidurk kitame pasaulyje, kur pojūčiai yra visai ne virtualūs! Pasiimk ir draugą, kad palaikytų už rankos, nes įspūdžių netrūks.", "slug" => "apie"],
            ["page_id" => "apie", "language_id" => "en", "title" => "About", "description_short" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems.", "description_long" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems - ir pirmą kartą išmėginsiantiems virtualią realybę, ir tiems, kurie jau žino kas tai yra. 10 skirtingų patirčių ir net 60 minučių įspūdžių, adrenalino ir atradimų laukia kiekvieno apsilankiusiojo. Paruošėme trijų skirtingų sudėtingumo lygių patirtis - nuo irklavimo Galvės ežere ar leidimosi parašiutu iki Mini golfo žaidimo ant pilies sienų ar stebuklingo gėrimo gamybos. Tačiau neabejojame, jog norėsi išbandyti visas. Virtuali realybė suteikia progą pažvelgti į pasaulį kitomis akimis ir iš paprasto stebėtojo virsti veiksmo dalyviu. Aukštos kokybės grafika, realūs vaizdai ir galimybė interaktyviai dalyvauti patirtyje tiesiog įtraukia! Tad ateik, užsidėk VR akinius ir atsidurk kitame pasaulyje, kur pojūčiai yra visai ne virtualūs! Pasiimk ir draugą, kad palaikytų už rankos, nes įspūdžių netrūks.", "slug" => "about"],
            ["page_id" => "apie", "language_id" => "ru", "title" => "O проекте", "description_short" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems.", "description_long" => "Virtuali realybė vis labiau skverbiasi į mūsų kasdienybę ir visas sritis nuo pramogų iki mokslo. todėl pristatome unikalią galimybę rytojų pamatyti jau dabar! Jaudinanti ir įtraukianti patirtis garantuota visiems - ir pirmą kartą išmėginsiantiems virtualią realybę, ir tiems, kurie jau žino kas tai yra. 10 skirtingų patirčių ir net 60 minučių įspūdžių, adrenalino ir atradimų laukia kiekvieno apsilankiusiojo. Paruošėme trijų skirtingų sudėtingumo lygių patirtis - nuo irklavimo Galvės ežere ar leidimosi parašiutu iki Mini golfo žaidimo ant pilies sienų ar stebuklingo gėrimo gamybos. Tačiau neabejojame, jog norėsi išbandyti visas. Virtuali realybė suteikia progą pažvelgti į pasaulį kitomis akimis ir iš paprasto stebėtojo virsti veiksmo dalyviu. Aukštos kokybės grafika, realūs vaizdai ir galimybė interaktyviai dalyvauti patirtyje tiesiog įtraukia! Tad ateik, užsidėk VR akinius ir atsidurk kitame pasaulyje, kur pojūčiai yra visai ne virtualūs! Pasiimk ir draugą, kad palaikytų už rankos, nes įspūdžių netrūks.", "slug" => "O_проекте"],
            ["page_id" => "kontaktai", "language_id" => "lt", "title" => "Kontaktai", "description_short" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'.", "description_long" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'. Bilietus galite įsigyti parodos kasoje.", "slug" => "kontaktai"],
            ["page_id" => "kontaktai", "language_id" => "en", "title" => "Contact", "description_short" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'.", "description_long" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'. Bilietus galite įsigyti parodos kasoje.", "slug" => "contact"],
            ["page_id" => "kontaktai", "language_id" => "ru", "title" => "Kонтакты", "description_short" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'.", "description_long" => "Paroda veiks nuo kovo mėn. 1 d. iki gegužės mėn. 31 d., Darbo laikas: darbo dienomis nuo 11 val. iki 22 val., savaitgaliais nuo 10 val. iki 22 val. Paroda vyksta, Vilniuje PC 'Akropolis', 2-ame aukšte, prie knygyno 'Pegasas'. Bilietus galite įsigyti parodos kasoje.", "slug" => "Kонтакты"],


            ["page_id" => "the_lab", "language_id" => "lt", "title" => "The Lab", "description_short" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "description_long" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "slug" => "the_lab_lt"],
            ["page_id" => "the_lab", "language_id" => "en", "title" => "The Lab", "description_short" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "description_long" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "slug" => "the_lab_en"],
            ["page_id" => "the_lab", "language_id" => "ru", "title" => "The Lab", "description_short" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "description_long" => "Tavo pilį puolą žvėriški barbarai, o tu turi tik lanką, kad juos sustabdytum. Tačiau tai viskas ko reikia tokiam patyrusiam kariui kaip tu - apsaugok savo pilį nuo priešų.", "slug" => "the_lab_ru"],

            ["page_id" => "fruit_ninja", "language_id" => "lt", "title" => "Fruit Ninja", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "slug" => "fruit_ninja_lt"],
            ["page_id" => "fruit_ninja", "language_id" => "en", "title" => "Fruit Ninja", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "slug" => "fruit_ninja_en"],
            ["page_id" => "fruit_ninja", "language_id" => "ru", "title" => "Fruit Ninja", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "slug" => "fruit_ninja_ru"],

            ["page_id" => "space_pirate_trainer", "language_id" => "lt", "title" => "Space Pirate Trainer", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Tai puiki proga išpildyti vaikystės svajonę būti kosmoso piratu. Čia išmoksi visko, ko tau reikės. Paimk skydą, nutaikyk ginklą ir pirmyn!", "slug" => "space_pirate_trainer_lt"],
            ["page_id" => "space_pirate_trainer", "language_id" => "en", "title" => "Space Pirate Trainer", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Tai puiki proga išpildyti vaikystės svajonę būti kosmoso piratu. Čia išmoksi visko, ko tau reikės. Paimk skydą, nutaikyk ginklą ir pirmyn!", "slug" => "space_pirate_trainer_en"],
            ["page_id" => "space_pirate_trainer", "language_id" => "ru", "title" => "Space Pirate Trainer", "description_short" => "Garsusis 'Fruit Ninja' žaidimas persikelia į virtualia realybę su dar daugiau smagumynų. Du kardai, 4 skirtingi rėžimai, nesuskaičiuojama gausa vaisių.", "description_long" => "Tai puiki proga išpildyti vaikystės svajonę būti kosmoso piratu. Čia išmoksi visko, ko tau reikės. Paimk skydą, nutaikyk ginklą ir pirmyn!", "slug" => "space_pirate_trainer_ru"],

            ["page_id" => "tilt_brush", "language_id" => "lt", "title" => "Tilt Brush", "description_short" => "Išbandyk savo piešimo įgūdžius 3D erdvėje! Nupiešk paveikslą ar žmogų, sukurk parką ar pastatyk namą. Ribų nėra! Išlaisvink kūrybiškumą!", "description_long" => "Išbandyk savo piešimo įgūdžius 3D erdvėje! Nupiešk paveikslą ar žmogų, sukurk parką ar pastatyk namą. Ribų nėra! Išlaisvink kūrybiškumą!", "slug" => "tilt_brush_lt"],
            ["page_id" => "tilt_brush", "language_id" => "en", "title" => "Tilt Brush", "description_short" => "Išbandyk savo piešimo įgūdžius 3D erdvėje! Nupiešk paveikslą ar žmogų, sukurk parką ar pastatyk namą. Ribų nėra! Išlaisvink kūrybiškumą!", "description_long" => "Išbandyk savo piešimo įgūdžius 3D erdvėje! Nupiešk paveikslą ar žmogų, sukurk parką ar pastatyk namą. Ribų nėra! Išlaisvink kūrybiškumą!", "slug" => "tilt_brush_en"],
            ["page_id" => "tilt_brush", "language_id" => "ru", "title" => "Tilt Brush", "description_short" => "Išbandyk savo piešimo įgūdžius 3D erdvėje! Nupiešk paveikslą ar žmogų, sukurk parką ar pastatyk namą. Ribų nėra! Išlaisvink kūrybiškumą!", "description_long" => "Išbandyk savo piešimo įgūdžius 3D erdvėje! Nupiešk paveikslą ar žmogų, sukurk parką ar pastatyk namą. Ribų nėra! Išlaisvink kūrybiškumą!", "slug" => "tilt_brush_ru"],

            ["page_id" => "merry_snowballs", "language_id" => "lt", "title" => "Merry Snowballs", "description_short" => "Išpildyk vaikystės svajonę ir pasinerk į nepakartojamą sniego karą.", "description_long" => "Išpildyk vaikystės svajonę ir pasinerk į nepakartojamą sniego karą. Apsisaugok nuo kitų gniūžčių su šiukšlių dėžės dangčiu arba pasislėpdamas už tvoros. O sniego šautuvas padės įrodyti, kad esi kiečiausias vaikas kieme.", "slug" => "merry_snowballs_lt"],
            ["page_id" => "merry_snowballs", "language_id" => "en", "title" => "Merry Snowballs", "description_short" => "Išpildyk vaikystės svajonę ir pasinerk į nepakartojamą sniego karą.", "description_long" => "Išpildyk vaikystės svajonę ir pasinerk į nepakartojamą sniego karą. Apsisaugok nuo kitų gniūžčių su šiukšlių dėžės dangčiu arba pasislėpdamas už tvoros. O sniego šautuvas padės įrodyti, kad esi kiečiausias vaikas kieme.", "slug" => "merry_snowballs_en"],
            ["page_id" => "merry_snowballs", "language_id" => "ru", "title" => "Merry Snowballs", "description_short" => "Išpildyk vaikystės svajonę ir pasinerk į nepakartojamą sniego karą.", "description_long" => "Išpildyk vaikystės svajonę ir pasinerk į nepakartojamą sniego karą. Apsisaugok nuo kitų gniūžčių su šiukšlių dėžės dangčiu arba pasislėpdamas už tvoros. O sniego šautuvas padės įrodyti, kad esi kiečiausias vaikas kieme.", "slug" => "merry_snowballs_ru"],

            ["page_id" => "samsung_irklavimas", "language_id" => "lt", "title" => "Samsung Irklavimas", "description_short" => "Išbandyk savo jėgas irkluodamas Trakų ežere su Rio olimpiados vicečempionu Saulius Ritter.", "description_long" => "Išbandyk savo jėgas irkluodamas Trakų ežere su Rio olimpiados vicečempionu Saulius Ritter.", "slug" => "samsung_irklavimas_lt"],
            ["page_id" => "samsung_irklavimas", "language_id" => "en", "title" => "Samsung Rowing", "description_short" => "Išbandyk savo jėgas irkluodamas Trakų ežere su Rio olimpiados vicečempionu Saulius Ritter.", "description_long" => "Išbandyk savo jėgas irkluodamas Trakų ežere su Rio olimpiados vicečempionu Saulius Ritter.", "slug" => "samsung_irklavimas_en"],
            ["page_id" => "samsung_irklavimas", "language_id" => "ru", "title" => "Samsung гребля", "description_short" => "Išbandyk savo jėgas irkluodamas Trakų ežere su Rio olimpiados vicečempionu Saulius Ritter.", "description_long" => "Išbandyk savo jėgas irkluodamas Trakų ežere su Rio olimpiados vicečempionu Saulius Ritter.", "slug" => "samsung_irklavimas_ru"],

            ["page_id" => "ktu_parasparnis", "language_id" => "lt", "title" => "KTU parasparnis", "description_short" => "Suvaldyk parasparnį ant KTU pastato nesugadindamas. Daugiau lankų surinksi pakeliui - daugiau taškų pelnysi.", "description_long" => "Suvaldyk parasparnį ant KTU pastato nesugadindamas. Daugiau lankų surinksi pakeliui - daugiau taškų pelnysi.", "slug" => "ktu_parasparnis_lt"],
            ["page_id" => "ktu_parasparnis", "language_id" => "en", "title" => "KTU Glider", "description_short" => "Suvaldyk parasparnį ant KTU pastato nesugadindamas. Daugiau lankų surinksi pakeliui - daugiau taškų pelnysi.", "description_long" => "Suvaldyk parasparnį ant KTU pastato nesugadindamas. Daugiau lankų surinksi pakeliui - daugiau taškų pelnysi.", "slug" => "ktu_parasparnis_en"],
            ["page_id" => "ktu_parasparnis", "language_id" => "ru", "title" => "KTU планер", "description_short" => "Suvaldyk parasparnį ant KTU pastato nesugadindamas. Daugiau lankų surinksi pakeliui - daugiau taškų pelnysi.", "description_long" => "Suvaldyk parasparnį ant KTU pastato nesugadindamas. Daugiau lankų surinksi pakeliui - daugiau taškų pelnysi.", "slug" => "ktu_parasparnis_ru"],

            ["page_id" => "hurl", "language_id" => "lt", "title" => "Hurl", "description_short" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį.", "description_long" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį. Tiesa, prieš pasiekdamas lanką, kamuolys turi atsitrenkti į tam tikrą kiekį platformų.", "slug" => "hurl_lt"],
            ["page_id" => "hurl", "language_id" => "en", "title" => "Hurl", "description_short" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį.", "description_long" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį. Tiesa, prieš pasiekdamas lanką, kamuolys turi atsitrenkti į tam tikrą kiekį platformų.", "slug" => "hurl_en"],
            ["page_id" => "hurl", "language_id" => "ru", "title" => "Hurl", "description_short" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį.", "description_long" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį. Tiesa, prieš pasiekdamas lanką, kamuolys turi atsitrenkti į tam tikrą kiekį platformų.", "slug" => "hurl_ru"],

            ["page_id" => "final_goalie_football_simulator", "language_id" => "lt", "title" => "Final Goalie: Football Simulator", "description_short" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui.", "description_long" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį. Tiesa, prieš pasiekdamas lanką, kamuolys turi atsitrenkti į tam tikrą kiekį platformų.", "slug" => "final_goalie_football_simulator_lt"],
            ["page_id" => "final_goalie_football_simulator", "language_id" => "en", "title" => "Final Goalie: Football Simulator", "description_short" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui.", "description_long" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį. Tiesa, prieš pasiekdamas lanką, kamuolys turi atsitrenkti į tam tikrą kiekį platformų.", "slug" => "final_goalie_football_simulator_en"],
            ["page_id" => "final_goalie_football_simulator", "language_id" => "ru", "title" => "Final Goalie: Football Simulator", "description_short" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui.", "description_long" => "Įmonės Telesoftas VR potyris, skirtas kamuolio gerbėjams - taigi kone kiekvienam lietuviui. Kol kas tai galvosūkių žaidimas, kuriame visos kliūtys įveikiamos tiesiog mėtant kamuolį. Tiesa, prieš pasiekdamas lanką, kamuolys turi atsitrenkti į tam tikrą kiekį platformų.", "slug" => "final_goalie_football_simulator_ru"],

            ["page_id" => "project_cars", "language_id" => "lt", "title" => "Project Cars", "description_short" => "Atsisėsk prie automobilio vairo ir parodyk, kad esi geriausias vairuotojas mieste. Vingiuoti posūkiai ir aršūs oponentai jau laukia tavęs!", "description_long" => "Atsisėsk prie automobilio vairo ir parodyk, kad esi geriausias vairuotojas mieste. Vingiuoti posūkiai ir aršūs oponentai jau laukia tavęs!", "slug" => "project_cars_lt"],
            ["page_id" => "project_cars", "language_id" => "en", "title" => "Project Cars", "description_short" => "Atsisėsk prie automobilio vairo ir parodyk, kad esi geriausias vairuotojas mieste. Vingiuoti posūkiai ir aršūs oponentai jau laukia tavęs!", "description_long" => "Atsisėsk prie automobilio vairo ir parodyk, kad esi geriausias vairuotojas mieste. Vingiuoti posūkiai ir aršūs oponentai jau laukia tavęs!", "slug" => "project_cars_en"],
            ["page_id" => "project_cars", "language_id" => "ru", "title" => "Project Cars", "description_short" => "Atsisėsk prie automobilio vairo ir parodyk, kad esi geriausias vairuotojas mieste. Vingiuoti posūkiai ir aršūs oponentai jau laukia tavęs!", "description_long" => "Atsisėsk prie automobilio vairo ir parodyk, kad esi geriausias vairuotojas mieste. Vingiuoti posūkiai ir aršūs oponentai jau laukia tavęs!", "slug" => "project_cars_ru"],

            ];

            DB::beginTransaction();
        try {
            foreach ($pagesTranslations as $pageData) {
                $role = VRPagesTranslations::where ('slug', $pageData['slug'])->first ();
                if (!$role)
                    VRPagesTranslations::create ($pageData);
            }
        } catch (\Exception $e) {
            DB::rollback();
            throw new Exception($e->getMessage());
        }
        DB::commit();
    }

}
